# Generated by Django 4.2.5 on 2024-05-08 23:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_padel', '0002_pista_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
