# Generated by Django 4.2.5 on 2024-05-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_padel', '0003_reserva_created_reserva_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
