# Generated by Django 4.2.5 on 2024-05-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_padel', '0004_alter_reserva_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='pista',
            name='descripcion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
