# Generated by Django 4.2.5 on 2024-05-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_padel', '0005_pista_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_disponibles', models.CharField(max_length=50)),
            ],
        ),
    ]
