# Generated by Django 4.2.5 on 2024-05-23 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_padel', '0005_detallesclub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='admin_id_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
