# Generated by Django 4.2.5 on 2024-05-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_padel', '0006_dimensiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='activo',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='pista',
            name='activo',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='reserva',
            name='activo',
            field=models.BooleanField(default=1),
        ),
    ]
